# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Digital_Circuit/Nexys4DDR_Master.xdc

# IP: ip/c_counter_binary_3/c_counter_binary_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_counter_binary_3 || ORIG_REF_NAME==c_counter_binary_3} -quiet] -quiet

# IP: ip/c_counter_binary_2/c_counter_binary_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_counter_binary_2 || ORIG_REF_NAME==c_counter_binary_2} -quiet] -quiet

# IP: ip/c_counter_binary_1/c_counter_binary_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_counter_binary_1 || ORIG_REF_NAME==c_counter_binary_1} -quiet] -quiet
